### ISSUE TITLE
Dead

### ISSUE THREAD

**Issue by retr0h** [eric/rubyrrdtool#1]
Is this dead?

Are there any plans to get this to work with rrd 1.3?

**Comment by eric** [comment]
It looks like someone made a change that works in 1.3:
http://github.com/gebi/rubyrrdtool/

I'm not sure if you'd consider the project dead or alive. I just put this up on github because it seemed like the easiest way to get my bug fix published.

**Comment by auxesis** [comment]
I'm willing to take up the release management of it. 

I've been familiarising myself with the code today and starting rewriting the test suite + documentation. 

I'm no C programmer, so when bugs come up I'll be hard pressed to come up with fixes (and thus am less inclined to completely take over maintainership).

That said, if other people are happy to provide bug fixes I'd be very happy to manage releases and whatnot.

**Comment by auxesis** [comment]
Can we rename the project also? 

Working out whether to use RRD or RRDtool is so confusing. 

I suggest Errand - you're making short trips to get data.

**Comment by eric** [comment]
I just kept with the name of the existing library, but I don't have a strong opinion.

**Comment by auxesis** [comment]
Ok rad.
